- hosts: all
  become: true
  roles:
    - { role: common, tags: common }

- hosts: teamspeak
  become: true
  roles:
    - docker
    - teamspeak

- hosts: cloud
  become: true
  roles:
    - docker
    - nextcloud
    - gotify
    - traggo
    - { role: ttrss, tags: ttrss }
    - { role: nginx-tls-proxy, tags: tls }
