- hosts: all
  become: true
  roles:
    - common

- hosts: teamspeak
  become: true
  roles:
    - docker
    - teamspeak

- hosts: cloud
  become: true
  roles:
    - docker
    - nextcloud
    - gotify
    - traggo
    - nginx-tls-proxy
