- hosts: all
  become: true
  roles:
    - { role: common, tags: common }
    - { role: sysupdate, tags: [never, sysupdate] }

- hosts: teamspeak
  become: true
  roles:
    - { role: docker, tags: deploy }
    - { role: teamspeak, tags: deploy }

- hosts: cloud
  become: true
  roles:
    - { role: docker, tags: deploy }
    - { role: nextcloud, tags: deploy }
    - { role: gotify, tags: deploy }
    - { role: traggo, tags: [deploy, traggo] }
    - { role: ttrss, tags: [deploy, ttrss] }
    - { role: nginx-tls-proxy, tags: [deploy, tls] }
    - { role: traggo-dev, tags: [deploy, traggo_dev] }
