- hosts: all
  become: true
  vars:
    # one of main, backup or apply-backup
    type: "main"
  tasks:
    - fail: msg="type must be one of main, backup and apply-backup"
      when: type != "main" and type != "backup" and type != "apply-backup"
    - include_role: name=common
      when: type == "main"
    - include_role: name=docker
      when: type == "main"

- hosts: teamspeak
  become: true
  vars:
    type: "main"
    teamspeak_dir: /var/ts3/
    sinusbot_dir: /var/sinusbot/
  tasks:
    - include_role: name=teamspeak tasks_from="{{ type }}"

- hosts: cloud
  become: true
  vars:
    type: "main"
    gotify_dir: "/var/gotify/"
    nextcloud_dir: "/var/nextcloud/"
    nginx_dir: "/var/nginx/"
  tasks:
    - include_role: name=nextcloud tasks_from="{{ type }}"
    - include_role: name=gotify tasks_from="{{ type }}"
    - include_role: name=nginx-tls-proxy
      when: type == "main"
