- name: "Stop Nextcloud"
  docker_container:
    name: "nextcloud"
    state: stopped
- name: "Upload Nextcloud Files"
  synchronize:
    mode: push
    src: backups/nextcloud/
    dest: "{{ nextcloud_dir }}"
- name: "Fix file perm"
  file:
    path: "{{ nextcloud_dir }}"
    owner: "http"
    recurse: yes
- name: "Restart Nextcloud"
  include_role:
    name: nextcloud

