- name: "Stop TS3"
  docker_container:
    name: "teamspeak"
    state: stopped
- name: "Stop Music Bot"
  docker_container:
    name: "sinusbot"
    state: stopped
- name: "Upload TS3 Files"
  synchronize:
    mode: push
    src: "{{ backup_dir }}/teamspeak/"
    dest: "{{ teamspeak_dir }}"
- name: "Upload Sinus Files"
  synchronize:
    mode: push
    src: "{{ backup_dir }}/sinusbot/"
    dest: "{{ sinusbot_dir }}"
- name: "Restart All"
  include_role:
    name: teamspeak

