- name: "Stop Gotify"
  docker_container:
    name: "gotify"
    state: stopped
- name: "Upload Gotify Files"
  synchronize:
    mode: push
    src: "{{ backup_dir}}/gotify/"
    dest: "{{ gotify_dir }}"
- name: "Restart Gotify"
  include_role:
    name: gotify

