- name: "ttrss network"
  docker_network:
    name: ttrss_network
- name: "start db"
  docker_container:
    name: "ttrss_db"
    image: "postgres:11.3-alpine"
    state: started
    restart: yes
    volumes:
      - "{{ ttrss_dir }}/db/:/var/lib/postgresql/data"
    env:
      POSTGRES_PASSWORD: "oopsie"
      POSTGRES_USER: "root"
      POSTGRES_DB: "ttrss"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    networks:
      - name: ttrss_network
- name: "start ttrss"
  docker_container:
    name: "ttrss"
    image: "linuxserver/tt-rss:19.8-ls32"
    state: started
    restart: yes
    networks:
      - name: ttrss_network
    volumes:
      - "{{ ttrss_dir }}/config/:/config/"
    env:
      VIRTUAL_HOST: "{{ ttrss_host }}"
      VIRTUAL_PORT: "80"
      LETSENCRYPT_HOST: "{{ ttrss_host }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt_email }}"
