- name: "traggo"
  docker_container:
    name: "traggo"
    image: "traggo/server:0.0.15"
    state: started
    restart: true
    exposed_ports:
      - "3030"
    env:
      VIRTUAL_HOST: "{{ traggo_host }}"
      VIRTUAL_PORT: "3030"
      LETSENCRYPT_HOST: "{{ traggo_host }}"
      LETSENCRYPT_EMAIL: "{{ letsencrypt_email }}"
    volumes:
      - "{{ traggo_dir }}:/opt/traggo/data"
